import React, { useEffect, useState } from 'react';
import { getCarbonTransactions, createCarbonTransaction, getDepartments, getEmissionFactors } from '../../services/api';
import type { CarbonTransaction, Department, EmissionFactor } from '../../types';
import { Card } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { DataTable } from '../../components/ui/DataTable';
import { Modal } from '../../components/ui/Modal';
import { Plus } from 'lucide-react';

export const CarbonTransactions: React.FC = () => {
  const [transactions, setTransactions] = useState<CarbonTransaction[]>([]);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [factors, setFactors] = useState<EmissionFactor[]>([]);
  const [loading, setLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);

  // Form states
  const [departmentId, setDepartmentId] = useState('');
  const [emissionFactorId, setEmissionFactorId] = useState('');
  const [sourceType, setSourceType] = useState('Electricity');
  const [quantity, setQuantity] = useState(0);
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [notes, setNotes] = useState('');

  const fetchTransactions = async () => {
    try {
      const res = await getCarbonTransactions();
      setTransactions(res.data.data);
    } catch (err) {
      console.error('Error fetching transactions:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const fetchMetadata = async () => {
      try {
        const [deptRes, efRes] = await Promise.all([getDepartments(), getEmissionFactors()]);
        setDepartments(deptRes.data.data);
        setFactors(efRes.data.data);
        if (deptRes.data.data.length > 0) setDepartmentId(deptRes.data.data[0].id);
        if (efRes.data.data.length > 0) {
          setEmissionFactorId(efRes.data.data[0].id);
          setSourceType(efRes.data.data[0].source_type);
        }
      } catch (err) {
        console.error('Error fetching metadata:', err);
      }
    };
    fetchMetadata();
    fetchTransactions();
  }, []);

  const handleFactorChange = (factorId: string) => {
    setEmissionFactorId(factorId);
    const selected = factors.find(f => f.id === factorId);
    if (selected) {
      setSourceType(selected.source_type);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await createCarbonTransaction({
        department_id: departmentId,
        emission_factor_id: emissionFactorId,
        source_type: sourceType,
        quantity: Number(quantity),
        date,
        notes
      });
      setIsModalOpen(false);
      setQuantity(0);
      setNotes('');
      fetchTransactions();
    } catch (err) {
      console.error('Error creating transaction:', err);
    }
  };

  const columns = [
    {
      header: 'Date',
      accessor: (row: CarbonTransaction) => <span>{row.date}</span>,
      sortKey: 'date' as any
    },
    {
      header: 'Department',
      accessor: (row: CarbonTransaction) => <span>{row.departments?.name || '-'}</span>
    },
    {
      header: 'Source',
      accessor: (row: CarbonTransaction) => <span style={{ fontWeight: 600, color: '#fff' }}>{row.source_type}</span>,
      sortKey: 'source_type' as any
    },
    {
      header: 'Quantity',
      accessor: (row: CarbonTransaction) => <span>{row.quantity} {row.emission_factors?.unit}</span>
    },
    {
      header: 'Calculated Emission',
      accessor: (row: CarbonTransaction) => (
        <span style={{ color: 'var(--danger)', fontWeight: 600 }}>
          {row.calculated_emission?.toLocaleString()} kg CO2e
        </span>
      ),
      sortKey: 'calculated_emission' as any
    },
    {
      header: 'Type',
      accessor: (row: CarbonTransaction) => (
        <span style={{ fontSize: '0.8rem', color: row.auto_calculated ? 'var(--success)' : 'var(--text-secondary)' }}>
          {row.auto_calculated ? 'Auto' : 'Manual'}
        </span>
      )
    }
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h2 style={{ fontSize: '1.8rem', fontWeight: 800, color: '#fff', letterSpacing: '-0.5px' }}>
            Carbon Transactions
          </h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginTop: '4px' }}>
            Log and audit calculations for greenhouse gas outputs generated by operational areas.
          </p>
        </div>
        <Button onClick={() => setIsModalOpen(true)}>
          <Plus size={16} /> Log Emissions
        </Button>
      </div>

      <Card>
        {loading ? (
          <div style={{ color: 'var(--text-secondary)' }}>Loading transactions...</div>
        ) : (
          <DataTable
            columns={columns}
            data={transactions}
            searchPlaceholder="Search by source..."
            searchFilter={(row, query) => row.source_type.toLowerCase().includes(query.toLowerCase())}
          />
        )}
      </Card>

      {/* Add Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title="Log Carbon Transaction"
        footerActions={
          <>
            <Button variant="secondary" onClick={() => setIsModalOpen(false)}>Cancel</Button>
            <Button onClick={handleSubmit}>Log Transaction</Button>
          </>
        }
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
            <label style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-secondary)' }}>Department</label>
            <select value={departmentId} onChange={(e) => setDepartmentId(e.target.value)} required>
              {departments.map((d) => (
                <option key={d.id} value={d.id}>{d.name}</option>
              ))}
            </select>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
            <label style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-secondary)' }}>Emission Source (Factor)</label>
            <select value={emissionFactorId} onChange={(e) => handleFactorChange(e.target.value)} required>
              {factors.map((f) => (
                <option key={f.id} value={f.id}>{f.source_type} ({f.region || 'Global'})</option>
              ))}
            </select>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
            <label style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-secondary)' }}>Quantity</label>
            <input type="number" step="0.1" value={quantity} onChange={(e) => setQuantity(Number(e.target.value))} required />
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
            <label style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-secondary)' }}>Date</label>
            <input type="date" value={date} onChange={(e) => setDate(e.target.value)} required />
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
            <label style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-secondary)' }}>Notes</label>
            <input type="text" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="e.g. Monthly utility bill" />
          </div>
        </div>
      </Modal>
    </div>
  );
};
